### ISSUE TITLE
HTTP Error 500 thrown when retrieving contract

### ISSUE THREAD

**Issue by eosBlockSmith** [SnaxFoundation/SnaxTracker#9]
Steps to reproduce:

1. Go to the explorer and search for an account (i.e. [https://explorer.snax.one/accounts/snax](https://explorer.snax.one/accounts/snax))
2. Click "<> Contract" tab
3. Observe the returned error.

**Comment by eosBlockSmith** [comment]
Might actually be related to [https://github.com/SnaxFoundation/snax](https://github.com/SnaxFoundation/snax) but the error showed up in the explorer.

**Comment by ant-mad** [comment]
Fixed in last version
